/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ex02;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JRadioButton;
import javax.swing.JRadioButtonMenuItem;

/**
 *
 * @author dti
 */
public class Frame extends javax.swing.JFrame {
     
   Integer tamanhoFont =12;
    Integer estiloFont = Font.PLAIN;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        grupoBotao.add(radio12);
        grupoBotao.add(radio14);
        grupoBotao.add(radio16);
        grupoBotao.add(radio18);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotao = new javax.swing.ButtonGroup();
        txtArea = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        barraMenu = new javax.swing.JMenuBar();
        menuOpcao = new javax.swing.JMenu();
        menItemSair = new javax.swing.JMenuItem();
        menuFonte = new javax.swing.JMenu();
        menuCor = new javax.swing.JMenu();
        menuItemSemcor = new javax.swing.JMenuItem();
        menuItemAzul = new javax.swing.JMenuItem();
        menuItemVerde = new javax.swing.JMenuItem();
        menuItemVermelho = new javax.swing.JMenuItem();
        menuItemAmarelo = new javax.swing.JMenuItem();
        menuItemPreto = new javax.swing.JMenuItem();
        menuEstilo = new javax.swing.JMenu();
        estiloNormal = new javax.swing.JCheckBoxMenuItem();
        estiloNegrito = new javax.swing.JCheckBoxMenuItem();
        estiloItalico = new javax.swing.JCheckBoxMenuItem();
        estiloNegritoItalico = new javax.swing.JCheckBoxMenuItem();
        menuTamanho = new javax.swing.JMenu();
        radio12 = new javax.swing.JRadioButtonMenuItem();
        radio14 = new javax.swing.JRadioButtonMenuItem();
        radio16 = new javax.swing.JRadioButtonMenuItem();
        radio18 = new javax.swing.JRadioButtonMenuItem();
        menItemLimpar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto.setColumns(20);
        texto.setRows(5);
        txtArea.setViewportView(texto);

        menuOpcao.setText("Opções");

        menItemSair.setText("Sair");
        menuOpcao.add(menItemSair);

        menuFonte.setText("Fonte");

        menuCor.setText("Cor");

        menuItemSemcor.setText("Sem Cor");
        menuItemSemcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSemcorActionPerformed(evt);
            }
        });
        menuCor.add(menuItemSemcor);

        menuItemAzul.setText("Azul");
        menuItemAzul.setToolTipText("");
        menuItemAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAzulActionPerformed(evt);
            }
        });
        menuCor.add(menuItemAzul);

        menuItemVerde.setText("Verde");
        menuItemVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerdeActionPerformed(evt);
            }
        });
        menuCor.add(menuItemVerde);

        menuItemVermelho.setText("Vermelho");
        menuItemVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVermelhoActionPerformed(evt);
            }
        });
        menuCor.add(menuItemVermelho);

        menuItemAmarelo.setText("Amarelo");
        menuItemAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAmareloActionPerformed(evt);
            }
        });
        menuCor.add(menuItemAmarelo);

        menuItemPreto.setText("Preto");
        menuItemPreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretoActionPerformed(evt);
            }
        });
        menuCor.add(menuItemPreto);

        menuFonte.add(menuCor);

        menuEstilo.setText("Estilo");

        estiloNormal.setSelected(true);
        estiloNormal.setText("Normal");
        estiloNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estiloNormalActionPerformed(evt);
            }
        });
        menuEstilo.add(estiloNormal);

        estiloNegrito.setText("Negrito");
        estiloNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estiloNegritoActionPerformed(evt);
            }
        });
        menuEstilo.add(estiloNegrito);

        estiloItalico.setText("Itálico");
        estiloItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estiloItalicoActionPerformed(evt);
            }
        });
        menuEstilo.add(estiloItalico);

        estiloNegritoItalico.setText("Negrito e Itálico");
        estiloNegritoItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estiloNegritoItalicoActionPerformed(evt);
            }
        });
        menuEstilo.add(estiloNegritoItalico);

        menuFonte.add(menuEstilo);

        menuTamanho.setText("Tamanho");

        radio12.setSelected(true);
        radio12.setText("12");
        radio12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio12ActionPerformed(evt);
            }
        });
        menuTamanho.add(radio12);

        radio14.setText("14");
        menuTamanho.add(radio14);

        radio16.setText("16");
        menuTamanho.add(radio16);

        radio18.setText("18");
        menuTamanho.add(radio18);

        menuFonte.add(menuTamanho);

        menuOpcao.add(menuFonte);

        menItemLimpar.setText("Limpar");
        menItemLimpar.setToolTipText("");
        menItemLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menItemLimparActionPerformed(evt);
            }
        });
        menuOpcao.add(menItemLimpar);

        barraMenu.add(menuOpcao);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menItemLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menItemLimparActionPerformed
        menItemLimpar.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        texto.setText("");
                        texto.requestFocus();
                    }
                }
        );
        
    }//GEN-LAST:event_menItemLimparActionPerformed

    private void menuItemSemcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSemcorActionPerformed
        menuItemSemcor.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        texto.setForeground(Color.black);
                        repaint();
                    }
                }
        );
    }//GEN-LAST:event_menuItemSemcorActionPerformed

    private void menuItemAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAzulActionPerformed
        menuItemAzul.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        texto.setForeground(Color.blue);
                        repaint();
                    }
                }
        );
    }//GEN-LAST:event_menuItemAzulActionPerformed

    private void menuItemVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerdeActionPerformed
        menuItemVerde.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        texto.setForeground(Color.green);
                        repaint();
                    }
                }
        );
    }//GEN-LAST:event_menuItemVerdeActionPerformed

    private void menuItemVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVermelhoActionPerformed
        menuItemVermelho.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        texto.setForeground(Color.red);
                        repaint();
                    }
                }
        );
    }//GEN-LAST:event_menuItemVermelhoActionPerformed

    private void menuItemAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAmareloActionPerformed
        menuItemAmarelo.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        texto.setForeground(Color.yellow);
                        repaint();
                    }
                }
        );
    }//GEN-LAST:event_menuItemAmareloActionPerformed

    private void menuItemPretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretoActionPerformed
        menuItemPreto.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        texto.setForeground(Color.black);
                        repaint();
                    }
                }
        );
    }//GEN-LAST:event_menuItemPretoActionPerformed

    private void estiloNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estiloNormalActionPerformed
        estiloNormal.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        estiloFont = Font.PLAIN;
                        texto.setFont(new Font("" , estiloFont , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_estiloNormalActionPerformed

    private void estiloNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estiloNegritoActionPerformed
        estiloNegrito.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        estiloFont = Font.BOLD;
                        texto.setFont(new Font("" , estiloFont , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_estiloNegritoActionPerformed

    private void estiloItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estiloItalicoActionPerformed
        estiloItalico.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        estiloFont = Font.ITALIC;
                        texto.setFont(new Font("" , estiloFont , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_estiloItalicoActionPerformed

    private void estiloNegritoItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estiloNegritoItalicoActionPerformed
        estiloNegritoItalico.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        estiloFont = Font.BOLD+Font.ITALIC;
                        texto.setFont(new Font("" , estiloFont , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_estiloNegritoItalicoActionPerformed

    private void radio12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JCheckBoxMenuItem estiloItalico;
    private javax.swing.JCheckBoxMenuItem estiloNegrito;
    private javax.swing.JCheckBoxMenuItem estiloNegritoItalico;
    private javax.swing.JCheckBoxMenuItem estiloNormal;
    private javax.swing.ButtonGroup grupoBotao;
    private javax.swing.JMenuItem menItemLimpar;
    private javax.swing.JMenuItem menItemSair;
    private javax.swing.JMenu menuCor;
    private javax.swing.JMenu menuEstilo;
    private javax.swing.JMenu menuFonte;
    private javax.swing.JMenuItem menuItemAmarelo;
    private javax.swing.JMenuItem menuItemAzul;
    private javax.swing.JMenuItem menuItemPreto;
    private javax.swing.JMenuItem menuItemSemcor;
    private javax.swing.JMenuItem menuItemVerde;
    private javax.swing.JMenuItem menuItemVermelho;
    private javax.swing.JMenu menuOpcao;
    private javax.swing.JMenu menuTamanho;
    private javax.swing.JRadioButtonMenuItem radio12;
    private javax.swing.JRadioButtonMenuItem radio14;
    private javax.swing.JRadioButtonMenuItem radio16;
    private javax.swing.JRadioButtonMenuItem radio18;
    private javax.swing.JTextArea texto;
    private javax.swing.JScrollPane txtArea;
    // End of variables declaration//GEN-END:variables
}
