/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ex01;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author dti
 */
public class Frame extends javax.swing.JFrame {
    Integer estilo = Font.PLAIN;
    Integer tamanhoFont = 12;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        grupoBotao.add(rad12);
        grupoBotao.add(rad14);
        grupoBotao.add(rad16);
        grupoBotao.add(rad18);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotao = new javax.swing.ButtonGroup();
        lblCor = new javax.swing.JLabel();
        lblEstilo = new javax.swing.JLabel();
        lblTamanho = new javax.swing.JLabel();
        cbrCor = new javax.swing.JComboBox<>();
        cbxNegrito = new javax.swing.JCheckBox();
        cbxItalico = new javax.swing.JCheckBox();
        cbxNormal = new javax.swing.JCheckBox();
        rad12 = new javax.swing.JRadioButton();
        rad14 = new javax.swing.JRadioButton();
        rad16 = new javax.swing.JRadioButton();
        rad18 = new javax.swing.JRadioButton();
        lblTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCor.setText("Cor");

        lblEstilo.setText("Estilo");

        lblTamanho.setText("Tamanho");

        cbrCor.setMaximumRowCount(7);
        cbrCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem Cor", "Vermelho", "Azul", "Verde", "Amarelo", "Branco", "Preto" }));
        cbrCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrCorActionPerformed(evt);
            }
        });

        cbxNegrito.setText("Negrito");
        cbxNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNegritoActionPerformed(evt);
            }
        });

        cbxItalico.setText("Italico");
        cbxItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxItalicoActionPerformed(evt);
            }
        });

        cbxNormal.setText("Normal");
        cbxNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNormalActionPerformed(evt);
            }
        });

        rad12.setText("12");
        rad12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad12ActionPerformed(evt);
            }
        });

        rad14.setText("14");
        rad14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad14ActionPerformed(evt);
            }
        });

        rad16.setText("16");
        rad16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad16ActionPerformed(evt);
            }
        });

        rad18.setText("18");
        rad18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad18ActionPerformed(evt);
            }
        });

        lblTexto.setText("Programa Feito em Java");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTexto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCor)
                                .addGap(139, 139, 139)
                                .addComponent(lblEstilo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbrCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxNegrito)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxItalico)
                                            .addComponent(cbxNormal))
                                        .addGap(2, 2, 2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTamanho)
                            .addComponent(rad12)
                            .addComponent(rad16)
                            .addComponent(rad14)
                            .addComponent(rad18))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCor)
                            .addComponent(lblTamanho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbrCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rad12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblEstilo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxNegrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxItalico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxNormal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(lblTexto)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbrCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrCorActionPerformed
        cbrCor.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        if(cbrCor.getSelectedItem().toString() == "Sem Cor"){
                            lblTexto.setForeground(Color.black);
                        }
                        
                        if(cbrCor.getSelectedItem().toString() == "Vermelho"){
                            lblTexto.setForeground(Color.red);
                        }
                        
                        if(cbrCor.getSelectedItem().toString() == "Azul"){
                            lblTexto.setForeground(Color.blue);
                        }
                        
                        if(cbrCor.getSelectedItem().toString() == "Verde"){
                            lblTexto.setForeground(Color.green);
                        }
                        
                        if(cbrCor.getSelectedItem().toString() == "Amarelo"){
                            lblTexto.setForeground(Color.yellow);
                        }
                        
                        if(cbrCor.getSelectedItem().toString() == "Branco"){
                            lblTexto.setForeground(Color.white);
                        }
                        
                        if(cbrCor.getSelectedItem().toString() == "Preto"){
                            lblTexto.setForeground(Color.black);
                        }
                    }
                }
        );
    }//GEN-LAST:event_cbrCorActionPerformed

    private void rad12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad12ActionPerformed
        rad12.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        tamanhoFont = 12;
                        lblTexto.setFont(new Font("" , estilo , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_rad12ActionPerformed

    private void rad14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad14ActionPerformed
        rad14.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        tamanhoFont = 14;
                        lblTexto.setFont(new Font("" , estilo , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_rad14ActionPerformed

    private void rad16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad16ActionPerformed
        rad16.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        tamanhoFont = 16;
                        lblTexto.setFont(new Font("" , estilo , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_rad16ActionPerformed

    private void rad18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad18ActionPerformed
        rad18.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        tamanhoFont = 18;
                        lblTexto.setFont(new Font("" , estilo , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_rad18ActionPerformed

    private void cbxNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNegritoActionPerformed
        cbxNegrito.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        estilo = Font.BOLD;
                        cbxNormal.setSelected(false);
                        cbxItalico.setSelected(false);
                        
                        lblTexto.setFont(new Font("" , estilo , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_cbxNegritoActionPerformed

    private void cbxItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItalicoActionPerformed
        cbxItalico.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        estilo = Font.ITALIC;
                        cbxNormal.setSelected(false);
                        cbxNegrito.setSelected(false);
                        
                        lblTexto.setFont(new Font("" , estilo , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_cbxItalicoActionPerformed

    private void cbxNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNormalActionPerformed
        cbxNormal.addActionListener(
                new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        estilo = Font.PLAIN;
                        cbxNegrito.setSelected(false);
                        cbxItalico.setSelected(false);
                        
                        lblTexto.setFont(new Font("" , estilo , tamanhoFont));
                    }
                }
        );
    }//GEN-LAST:event_cbxNormalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbrCor;
    private javax.swing.JCheckBox cbxItalico;
    private javax.swing.JCheckBox cbxNegrito;
    private javax.swing.JCheckBox cbxNormal;
    private javax.swing.ButtonGroup grupoBotao;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JRadioButton rad12;
    private javax.swing.JRadioButton rad14;
    private javax.swing.JRadioButton rad16;
    private javax.swing.JRadioButton rad18;
    // End of variables declaration//GEN-END:variables
}
