Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 

Var
peso,altura,imc:real

Inicio
//decoração
escreval ("************")
escreval ("Calculo IMC")
escreval ("************")
escreval ("")

escreva ("Digite o seu peso:")
leia(peso)
escreva ("Digite a sua altura:")
leia (altura)
imc<-peso/(altura*altura)
escreval ("Seu IMC é igual a" , imc)


Fimalgoritmo