Algoritmo "Algoritmo 1"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 



Var
a:real
perimetro:real

Inicio
//decoração
escreval("**********************")
escreval("Programa de Perimetro")
escreval("**********************")
escreval ("")


escreva ("Digite o valor do lado: ")
leia (a)
perimetro <-4*a

escreval ("O perimetro é" , perimetro)

Fimalgoritmo