Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 


Var
r, area: real



Inicio
//decoração
escreval ("**********************************")
escreval ("Programa calcular área do círculo")
escreval ("**********************************")
escreval ("")

escreva("Digite o valor do raio:")
leia(r)
area<-3.14*(r*r)
escreval ("A área de circunferencia é " ,area)


Fimalgoritmo