Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 


Var
celsius,kelvin:real

Inicio
//decoração
escreval ("*************************************")
escreval ("Programa conversão celsius em kelvin")
escreval ("*************************************")
escreval ("")

escreva("Digite a temperatura em celsius:")
leia(celsius)
kelvin<-celsius+273,15
escreval ("")
escreval ("O valor em Kelvin é" ,kelvin)

Fimalgoritmo