Algoritmo "Algoritmo 2"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 

Var
a,b,soma:inteiro


Inicio
//decoração
escreval("*****************")
escreval("Programa de Soma")
escreval("*****************")
escreval("")


escreva("Digite o primeiro valor:")
leia(a)
escreva("Digite o segundo valor:")
leia (b)
soma<-a+b
escreval ("A soma dos valores é" ,soma)

Fimalgoritmo