Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 


Var
a,b,m:real


Inicio
//decoração
escreval ("************************")
escreval ("Programa calcular média")
escreval ("************************")
escreval ("")

escreva ("Digite um valor para a variavel A:")
leia (a)
escreva ("Digite um valor para a variavel B:")
leia (b)
m<-(a+b)/2
escreval ("A média dos valores é" ,m)



Fimalgoritmo